create table branches (
    id bigint generated by default as identity primary key,
    code varchar(255) not null unique,
    name varchar(255) not null,
    address varchar(255),
    phone varchar(255),
    active boolean not null
);

create table app_users (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    role varchar(40) not null,
    active boolean not null,
    last_login_at timestamp,
    created_at timestamp,
    constraint fk_users_branch foreign key (branch_id) references branches(id)
);

create table products (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    sku varchar(255),
    name varchar(255) not null,
    category varchar(255) not null,
    description varchar(255),
    price numeric(12,2) not null,
    cost numeric(12,2) not null,
    accent varchar(255),
    prep_minutes integer,
    available_for_half boolean not null,
    active boolean not null,
    constraint fk_products_branch foreign key (branch_id) references branches(id)
);

create table product_variants (
    product_id bigint not null,
    variant_name varchar(255),
    price_adjustment numeric(12,2),
    constraint fk_variants_product foreign key (product_id) references products(id) on delete cascade
);

create table customers (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    name varchar(255) not null,
    phone varchar(255),
    email varchar(255),
    address varchar(255),
    birthday date,
    loyalty_points integer not null,
    total_spent numeric(12,2),
    last_order_at timestamp,
    marketing_opt_in boolean not null,
    orders_count integer not null,
    created_at timestamp,
    constraint fk_customers_branch foreign key (branch_id) references branches(id)
);

create table dining_tables (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    table_number integer not null,
    seats integer,
    area varchar(255),
    qr_token varchar(255) unique,
    status varchar(40),
    constraint uk_table_branch_number unique (branch_id, table_number),
    constraint fk_tables_branch foreign key (branch_id) references branches(id)
);

create table inventory_items (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    name varchar(255) not null,
    unit varchar(255),
    quantity numeric(12,3) not null,
    minimum_quantity numeric(12,3) not null,
    supplier varchar(255),
    supplier_id bigint,
    barcode varchar(255),
    cost_per_unit numeric(12,4),
    expires_at date,
    constraint fk_inventory_branch foreign key (branch_id) references branches(id)
);

create table finance_entries (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    description varchar(255),
    category varchar(255),
    type varchar(40),
    status varchar(40),
    amount numeric(12,2),
    due_date date,
    paid_at date,
    payment_method varchar(255),
    reference_code varchar(255),
    constraint fk_finance_branch foreign key (branch_id) references branches(id)
);

create table sale_orders (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    code varchar(255) not null unique,
    status varchar(40) not null,
    type varchar(40) not null,
    table_number integer,
    customer_name varchar(255),
    customer_id bigint,
    customer_phone varchar(255),
    delivery_address varchar(255),
    delivery_driver varchar(255),
    payment_method varchar(255),
    coupon_code varchar(255),
    notes varchar(255),
    subtotal numeric(12,2) not null,
    discount numeric(12,2) not null,
    delivery_fee numeric(12,2) not null,
    service_fee numeric(12,2) not null,
    total numeric(12,2) not null,
    paid_amount numeric(12,2) not null,
    change_amount numeric(12,2) not null,
    estimated_at timestamp,
    started_at timestamp,
    ready_at timestamp,
    completed_at timestamp,
    created_by varchar(255),
    stock_deducted boolean not null,
    loyalty_processed boolean not null,
    created_at timestamp,
    constraint fk_orders_branch foreign key (branch_id) references branches(id)
);

create table sale_order_lines (
    order_id bigint not null,
    product_id bigint,
    product_name varchar(255),
    quantity integer,
    unit_price numeric(38,2),
    unit_cost numeric(38,2),
    variant_name varchar(255),
    half_product_id bigint,
    half_product_name varchar(255),
    modifiers varchar(255),
    notes varchar(255),
    line_total numeric(38,2),
    constraint fk_order_lines_order foreign key (order_id) references sale_orders(id) on delete cascade
);

create table sale_order_payments (
    order_id bigint not null,
    method varchar(255),
    amount numeric(38,2),
    constraint fk_order_payments_order foreign key (order_id) references sale_orders(id) on delete cascade
);

create table recipe_components (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    product_id bigint not null,
    inventory_item_id bigint not null,
    quantity numeric(12,4) not null,
    unit varchar(255),
    constraint uk_recipe_component unique (product_id, inventory_item_id),
    constraint fk_recipe_product foreign key (product_id) references products(id) on delete cascade,
    constraint fk_recipe_inventory foreign key (inventory_item_id) references inventory_items(id)
);

create table stock_movements (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    inventory_item_id bigint not null,
    inventory_item_name varchar(255),
    type varchar(40) not null,
    quantity numeric(12,4) not null,
    balance_after numeric(12,4) not null,
    reason varchar(255),
    reference_code varchar(255),
    performed_by varchar(255),
    created_at timestamp
);

create table suppliers (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    name varchar(255) not null,
    document varchar(255),
    contact_name varchar(255),
    phone varchar(255),
    email varchar(255),
    lead_time_days integer,
    active boolean not null,
    constraint fk_suppliers_branch foreign key (branch_id) references branches(id)
);

create table purchase_orders (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    code varchar(255) not null unique,
    supplier_id bigint,
    supplier_name varchar(255),
    status varchar(40) not null,
    expected_date date,
    received_date date,
    total numeric(12,2) not null,
    notes varchar(255),
    created_by varchar(255),
    created_at timestamp,
    constraint fk_purchases_branch foreign key (branch_id) references branches(id)
);

create table purchase_order_items (
    purchase_order_id bigint not null,
    inventory_item_id bigint,
    inventory_item_name varchar(255),
    quantity numeric(38,2),
    unit_cost numeric(38,2),
    line_total numeric(38,2),
    constraint fk_purchase_items_order foreign key (purchase_order_id) references purchase_orders(id) on delete cascade
);

create table cash_sessions (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    status varchar(40) not null,
    opening_amount numeric(12,2) not null,
    expected_amount numeric(12,2) not null,
    counted_amount numeric(12,2),
    difference_amount numeric(12,2),
    opened_by varchar(255),
    closed_by varchar(255),
    opened_at timestamp,
    closed_at timestamp,
    notes varchar(255),
    constraint fk_cash_branch foreign key (branch_id) references branches(id)
);

create table cash_movements (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    cash_session_id bigint not null,
    type varchar(40) not null,
    amount numeric(12,2) not null,
    description varchar(255),
    payment_method varchar(255),
    reference_code varchar(255),
    performed_by varchar(255),
    created_at timestamp,
    constraint fk_cash_movement_session foreign key (cash_session_id) references cash_sessions(id)
);

create table reservations (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    table_id bigint,
    table_number integer,
    customer_id bigint,
    customer_name varchar(255) not null,
    phone varchar(255),
    reserved_for timestamp not null,
    party_size integer,
    status varchar(40) not null,
    notes varchar(255),
    created_at timestamp,
    constraint fk_reservation_branch foreign key (branch_id) references branches(id)
);

create table loyalty_transactions (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    customer_id bigint not null,
    type varchar(40),
    points integer,
    description varchar(255),
    reference_code varchar(255),
    created_at timestamp
);

create table audit_events (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    actor varchar(255),
    action varchar(255) not null,
    entity_type varchar(255) not null,
    entity_id varchar(255),
    details varchar(2000),
    created_at timestamp
);

create table business_settings (
    id bigint generated by default as identity primary key,
    branch_id bigint not null unique,
    trade_name varchar(255),
    document varchar(255),
    phone varchar(255),
    address varchar(255),
    service_fee_percent numeric(5,2),
    minimum_delivery_order numeric(12,2),
    default_delivery_fee numeric(12,2),
    average_prep_minutes integer,
    max_delivery_radius_km integer,
    automatic_acceptance boolean not null,
    allow_notes boolean not null,
    print_ticket boolean not null,
    pix_enabled boolean not null,
    card_enabled boolean not null,
    cash_enabled boolean not null,
    pix_key varchar(255),
    constraint fk_settings_branch foreign key (branch_id) references branches(id)
);

create table coupons (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    code varchar(255) not null,
    description varchar(255),
    type varchar(40),
    discount_value numeric(12,2),
    valid_until date,
    active boolean not null,
    constraint uk_coupon_branch_code unique (branch_id, code)
);

create index idx_orders_branch_created on sale_orders(branch_id, created_at);
create index idx_stock_branch_created on stock_movements(branch_id, created_at);
create index idx_audit_branch_created on audit_events(branch_id, created_at);
create index idx_reservation_branch_date on reservations(branch_id, reserved_for);
