create table payment_charges (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    order_id bigint,
    provider varchar(40) not null,
    method varchar(40) not null,
    status varchar(40) not null,
    amount numeric(12,2) not null,
    external_reference varchar(255) not null unique,
    pix_copy_paste varchar(1000),
    expires_at timestamp,
    paid_at timestamp,
    created_at timestamp not null,
    constraint fk_charge_branch foreign key (branch_id) references branches(id),
    constraint fk_charge_order foreign key (order_id) references sale_orders(id)
);

create table customer_messages (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    customer_id bigint,
    order_id bigint,
    channel varchar(40) not null,
    status varchar(40) not null,
    recipient varchar(255) not null,
    template_code varchar(100),
    body varchar(2000) not null,
    provider_reference varchar(255),
    scheduled_at timestamp,
    sent_at timestamp,
    created_at timestamp not null,
    constraint fk_message_branch foreign key (branch_id) references branches(id),
    constraint fk_message_customer foreign key (customer_id) references customers(id),
    constraint fk_message_order foreign key (order_id) references sale_orders(id)
);

create table fiscal_documents (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    order_id bigint not null,
    status varchar(40) not null,
    document_type varchar(40) not null,
    provider varchar(80),
    access_key varchar(255),
    message varchar(1000),
    created_at timestamp not null,
    issued_at timestamp,
    constraint fk_fiscal_branch foreign key (branch_id) references branches(id),
    constraint fk_fiscal_order foreign key (order_id) references sale_orders(id)
);

create index idx_charge_branch_status on payment_charges(branch_id, status);
create index idx_message_branch_created on customer_messages(branch_id, created_at);
create index idx_fiscal_branch_order on fiscal_documents(branch_id, order_id);
