create table staff_shifts (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    user_id bigint not null,
    employee_name varchar(255) not null,
    status varchar(40) not null,
    started_at timestamp not null,
    ended_at timestamp,
    notes varchar(1000),
    constraint fk_shift_branch foreign key (branch_id) references branches(id),
    constraint fk_shift_user foreign key (user_id) references app_users(id)
);

create table customer_feedback (
    id bigint generated by default as identity primary key,
    branch_id bigint not null,
    order_id bigint not null unique,
    order_code varchar(255) not null,
    customer_name varchar(255),
    rating integer not null,
    comment varchar(1500),
    created_at timestamp not null,
    constraint fk_feedback_branch foreign key (branch_id) references branches(id),
    constraint fk_feedback_order foreign key (order_id) references sale_orders(id),
    constraint chk_feedback_rating check (rating between 1 and 5)
);

create index idx_shifts_branch_started on staff_shifts(branch_id, started_at);
create index idx_feedback_branch_created on customer_feedback(branch_id, created_at);
