import { useMemo, useState } from 'react';
import { Navigate } from 'react-router-dom';
import api from '../api/api';
import Icon from '../components/Icon';
import { Modal, PageHeader } from '../components/UI';
import { useApp } from '../context/AppContext';

const templates = [
  ['ORDER_RECEIVED', 'Pedido recebido', 'Olá, {cliente}! Recebemos seu pedido {pedido} e já vamos cuidar dele. 🍕'],
  ['ORDER_PREPARING', 'Em preparo', 'Seu pedido {pedido} entrou em preparo. A cozinha Aurora já está trabalhando nele.'],
  ['ORDER_READY', 'Pedido pronto', 'Seu pedido {pedido} está pronto. Obrigado por escolher a Aurora!'],
  ['ORDER_OUT_FOR_DELIVERY', 'Saiu para entrega', 'Seu pedido {pedido} saiu para entrega. Está quase aí! 🛵'],
  ['BIRTHDAY', 'Aniversário', 'Feliz aniversário, {cliente}! Temos uma surpresa especial esperando por você.'],
];

export default function AutomationsPage() {
  const { user, settings, saveSettings, customers, orders, notify, session } = useApp();
  const [selected, setSelected] = useState(templates[0]); const [history, setHistory] = useState([]); const [testing, setTesting] = useState(false); const [modal, setModal] = useState(false);
  if (!['ADMIN', 'MANAGER'].includes(user?.role)) return <Navigate to="/" replace />;
  const connected = Boolean(settings.whatsappConnected); const sandbox = settings.whatsappMode === 'SANDBOX';
  const recentPhone = customers.find(customer => customer.phone)?.phone || '';
  const activateSandbox = async () => { const next = { ...settings, whatsappConnected: true, whatsappMode: 'SANDBOX', whatsappPhoneNumber: settings.whatsappPhoneNumber || 'Sandbox Aurora' }; if (await saveSettings(next)) { notify('Ambiente de teste do WhatsApp ativado'); setModal(false); } };
  const disconnect = async () => { if (await saveSettings({ ...settings, whatsappConnected: false, whatsappMode: null })) notify('WhatsApp desconectado com segurança'); };
  const sendTest = async () => { setTesting(true); const payload = { channel: 'WHATSAPP', recipient: recentPhone, templateCode: selected[0], body: selected[2].replace('{cliente}', customers[0]?.name || 'Cliente').replace('{pedido}', orders[0]?.code || 'AP-TESTE') }; try { const result = session?.demo ? null : await api.post('/commerce/messages', payload); setHistory(current => [result?.data || { ...payload, id: Date.now(), status: 'QUEUED', createdAt: new Date().toISOString() }, ...current]); notify(sandbox ? 'Mensagem simulada e registrada na fila' : 'Mensagem colocada na fila de envio'); } catch { notify('API indisponível: simulação registrada somente nesta tela'); setHistory(current => [{ ...payload, id: Date.now(), status: 'QUEUED', createdAt: new Date().toISOString() }, ...current]); } finally { setTesting(false); } };
  const activeEvents = useMemo(() => templates.filter(item => item[0].startsWith('ORDER_')), []);
  return <div className="page-stack automations-page"><PageHeader eyebrow="Comunicação inteligente" title="Automações WhatsApp" description="Controle cada mensagem operacional e mantenha a experiência do cliente sempre informada." />
    <section className={`whatsapp-hero ${connected ? 'connected' : ''}`}><div><span className="whatsapp-mark">WA</span><small>WhatsApp Business</small><h2>{connected ? (sandbox ? 'Ambiente Sandbox ativo' : 'Canal conectado') : 'Canal ainda não conectado'}</h2><p>{connected ? 'Pedidos e mudanças de status podem gerar mensagens automáticas auditáveis.' : 'Ative o ambiente de teste agora; nenhuma mensagem é enviada para fora durante o Sandbox.'}</p></div><div className="whatsapp-actions">{connected ? <><span className="status-badge status-success">{sandbox ? 'Teste seguro' : 'Conectado'}</span><button type="button" className="button" onClick={disconnect}>Desconectar</button></> : <button type="button" className="button button-primary" onClick={() => setModal(true)}><Icon name="plus" />Configurar WhatsApp</button>}</div></section>
    <div className="automation-grid"><section className="panel"><div className="panel-header"><div><h3 className="panel-title">Eventos automáticos</h3><p className="panel-subtitle">Estas mensagens entram na fila ao longo da jornada do pedido.</p></div></div><div className="panel-body automation-events">{activeEvents.map(item => <button type="button" key={item[0]} className={selected[0] === item[0] ? 'active' : ''} onClick={() => setSelected(item)}><span><Icon name="check" /></span><div><strong>{item[1]}</strong><small>{item[2]}</small></div></button>)}</div></section><aside className="automation-preview"><span>Prévia do cliente</span><div className="message-bubble">{selected[2].replace('{cliente}', customers[0]?.name || 'Cliente').replace('{pedido}', orders[0]?.code || 'AP-TESTE')}</div><small>Variáveis são preenchidas pelo sistema ao disparar o evento.</small><button type="button" disabled={!connected || testing} className="button button-primary" onClick={sendTest}>{testing ? 'Enviando…' : 'Testar modelo na fila'}</button></aside></div>
    <section className="panel"><div className="panel-header"><div><h3 className="panel-title">Histórico de testes e automações</h3><p className="panel-subtitle">Toda comunicação fica registrada para rastreabilidade.</p></div></div><div className="panel-body automation-history">{history.length ? history.map(item => <div key={item.id}><span className="status-badge status-warning">Na fila</span><strong>{item.templateCode}</strong><small>{item.recipient} · {new Date(item.createdAt).toLocaleTimeString('pt-BR')}</small></div>) : <div className="automation-empty"><Icon name="sparkles" /><strong>Nenhum envio nesta sessão</strong><span>Ative o Sandbox e teste um modelo sem enviar mensagens reais.</span></div>}</div></section>
    {modal && <Modal title="Configurar WhatsApp Business" subtitle="Comece com segurança no ambiente de teste" onClose={() => setModal(false)}><div className="form-grid"><div className="integration-step full-span"><span>1</span><div><strong>Sandbox Aurora</strong><p>Simula a conexão, registra mensagens e permite validar automações sem telefone, token ou custo.</p></div></div><div className="integration-step full-span"><span>2</span><div><strong>Produção depois</strong><p>Para envio real, você precisará cadastrar o número, token e modelo aprovado da Meta no servidor.</p></div></div><div className="form-actions"><button type="button" className="button" onClick={() => setModal(false)}>Cancelar</button><button type="button" className="button button-primary" onClick={activateSandbox}>Ativar ambiente de teste</button></div></div></Modal>}
  </div>;
}
