import { useMemo, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import api from '../api/api';
import Icon from '../components/Icon';
import { Modal, PageHeader, Status } from '../components/UI';
import { money, useApp } from '../context/AppContext';

export default function CommercePage() {
  const { orders, customers, branchId, notify, session } = useApp();
  const [charges, setCharges] = useState([]); const [messages, setMessages] = useState([]); const [pix, setPix] = useState(null); const [tab, setTab] = useState('payments');
  const [messageForm, setMessageForm] = useState({ customerId: customers[0]?.id || '', body: 'Olá! Seu pedido Aurora está sendo preparado com carinho. 🍕', templateCode: 'ORDER_STATUS' });
  const openOrders = useMemo(() => orders.filter(order => !['COMPLETED','CANCELED','DELIVERED'].includes(order.status)), [orders]);
  const createPix = async order => {
    try {
      const response = session?.demo ? null : await api.post('/commerce/pix', { orderId: order.id });
      const charge = response?.data || { id: `demo-${Date.now()}`, orderId: order.id, amount: order.total, status: 'PENDING', externalReference: `AUR-PIX-${String(Date.now()).slice(-7)}`, pixCopyPaste: `000201-AURORA-${order.code}-${order.total}`, expiresAt: new Date(Date.now() + 30 * 60000).toISOString() };
      setCharges(current => [charge, ...current]); setPix(charge); notify(`PIX de ${money(charge.amount)} criado para ${order.code}`);
    } catch { notify('API indisponível: cobrança criada em modo demonstração'); }
  };
  const queueMessage = async event => {
    event.preventDefault(); const customer = customers.find(value => String(value.id) === String(messageForm.customerId));
    const payload = { ...messageForm, customerId: Number(messageForm.customerId), channel: 'WHATSAPP', recipient: customer?.phone };
    try { const response = session?.demo ? null : await api.post('/commerce/messages', payload); setMessages(current => [response?.data || { ...payload, id: Date.now(), status: 'QUEUED', recipient: customer?.phone, createdAt: new Date().toISOString() }, ...current]); notify('Mensagem colocada na fila de WhatsApp'); }
    catch { notify('Mensagem registrada localmente para demonstração'); setMessages(current => [{ ...payload, id: Date.now(), status: 'QUEUED', recipient: customer?.phone, createdAt: new Date().toISOString() }, ...current]); }
  };
  const fiscal = async order => { try { await api.post('/commerce/fiscal', { orderId: order.id, documentType: 'NFC_E', provider: 'A CONFIGURAR' }); } catch { /* demonstração sem API */ } notify(`NFC-e de ${order.code} preparada; falta somente configurar certificado e provedor fiscal.`); };
  const backup = async () => { try { const { data } = await api.get('/commerce/backup'); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `aurora-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); notify('Backup operacional exportado'); } catch { notify('Conecte a API para exportar o backup oficial'); } };
  return <div className="page-stack commerce-page"><PageHeader eyebrow="Receita conectada" title="Central comercial" description="Cobranças, relacionamento, fiscal e continuidade operacional em uma única central."><button type="button" className="button" onClick={backup}><Icon name="download" />Exportar backup</button></PageHeader>
    <div className="commerce-kpis"><article><span><Icon name="wallet" /></span><div><small>PIX pendentes</small><strong>{charges.filter(c => c.status === 'PENDING').length}</strong></div></article><article><span><Icon name="users" /></span><div><small>Mensagens em fila</small><strong>{messages.filter(m => m.status === 'QUEUED').length}</strong></div></article><article><span><Icon name="receipt" /></span><div><small>Pedidos acionáveis</small><strong>{openOrders.length}</strong></div></article></div>
    <div className="segmented commerce-tabs">{[['payments','Cobranças PIX'],['messages','WhatsApp & CRM'],['fiscal','Fiscal & continuidade']].map(([id,label]) => <button key={id} type="button" className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</div>
    {tab === 'payments' && <div className="commerce-grid"><section className="panel"><div className="panel-header"><div><h3 className="panel-title">Cobranças inteligentes</h3><p className="panel-subtitle">Gere um PIX por pedido e acompanhe o ciclo de pagamento.</p></div></div><div className="panel-body commerce-list">{openOrders.slice(0, 6).map(order => <div className="commerce-row" key={order.id}><div><strong>{order.code} · {order.customerName || 'Cliente balcão'}</strong><small>{money(order.total)} · {order.type === 'DELIVERY' ? 'Delivery' : order.type === 'DINE_IN' ? 'Salão' : 'Retirada'}</small></div><button type="button" className="button button-sm button-primary" onClick={() => createPix(order)}><Icon name="qr" />Gerar PIX</button></div>)}</div></section><aside className="commerce-aside"><Icon name="shield" /><strong>Conciliação segura</strong><p>O conector está pronto para Mercado Pago, Stone ou outro provedor. As credenciais ficam exclusivamente no servidor.</p><span>Sem dados de cartão no navegador.</span></aside></div>}
    {tab === 'messages' && <div className="commerce-grid"><section className="panel"><div className="panel-header"><div><h3 className="panel-title">Comunicação no momento certo</h3><p className="panel-subtitle">Envie confirmações e campanhas pelo WhatsApp Business quando o conector estiver ativado.</p></div></div><form className="panel-body form-grid" onSubmit={queueMessage}><label className="form-field full-span"><span className="form-label">Cliente</span><select value={messageForm.customerId} onChange={e => setMessageForm({ ...messageForm, customerId: e.target.value })}>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name} · {customer.phone}</option>)}</select></label><label className="form-field full-span"><span className="form-label">Mensagem</span><textarea rows="4" value={messageForm.body} onChange={e => setMessageForm({ ...messageForm, body: e.target.value })} /></label><div className="form-actions"><button className="button button-primary"><Icon name="arrow" />Colocar na fila</button></div></form></section><aside className="commerce-aside warm"><Icon name="sparkles" /><strong>Templates aprováveis</strong><p>Status do pedido, aniversário, recuperação de cliente e campanhas segmentadas ficam auditáveis antes do envio.</p><span>WhatsApp Business pronto para credenciais.</span></aside></div>}
    {tab === 'fiscal' && <section className="panel"><div className="panel-header"><div><h3 className="panel-title">Fiscal e resiliência</h3><p className="panel-subtitle">Documentos ficam preparados e a operação pode exportar uma cópia operacional a qualquer momento.</p></div></div><div className="panel-body commerce-list">{orders.slice(0, 8).map(order => <div className="commerce-row" key={order.id}><div><strong>NFC-e · {order.code}</strong><small>{money(order.total)} · emissão depende de certificado digital e provedor homologado</small></div><button type="button" className="button button-sm" onClick={() => fiscal(order)}><Icon name="receipt" />Preparar emissão</button></div>)}</div></section>}
    {pix && <Modal title="PIX criado" subtitle={`Cobrança ${pix.externalReference} válida por 30 minutos`} onClose={() => setPix(null)}><div className="pix-modal"><QRCodeSVG value={pix.pixCopyPaste} size={180} /><strong>{money(pix.amount)}</strong><small>Copie o código ou apresente o QR Code ao cliente.</small><textarea readOnly value={pix.pixCopyPaste} /><button type="button" className="button button-primary" onClick={() => { navigator.clipboard?.writeText(pix.pixCopyPaste); notify('Código PIX copiado'); }}>Copiar código PIX</button></div></Modal>}
  </div>;
}
