import { Link } from 'react-router-dom';
import Icon from '../components/Icon';
import { money, useApp } from '../context/AppContext';

export default function DashboardPage() {
  const { dashboard, orders, inventory } = useApp();
  const bars = dashboard.weeklyRevenue || []; const max = Math.max(...bars.map(x => Number(x.value)), 1);
  const active = orders.filter(o => !['COMPLETED', 'CANCELED'].includes(o.status)).slice(0, 4);
  const metrics = [['Faturamento de hoje', money(dashboard.revenueToday), 'trend', 'brand', '+18,4% vs. terça passada'], ['Pedidos em aberto', dashboard.openOrders, 'receipt', 'blue', '3 em produção agora'], ['Ticket médio', money(dashboard.averageTicket), 'wallet', 'green', '+6,2% neste mês'], ['Alertas de estoque', dashboard.lowStock, 'boxes', 'amber', 'Requer atenção hoje']];
  return <div className="page-stack">
    <section className="dashboard-hero"><div className="dashboard-hero-copy"><span className="page-eyebrow">Quarta-feira • Operação saudável</span><h1>Boa tarde, Davi.</h1><p>O salão está fluindo bem. Você faturou 18% a mais que no mesmo período da semana passada.</p></div><Link className="button button-primary button-lg" to="/pdv"><Icon name="plus" />Abrir novo pedido</Link></section>
    <div className="metrics-grid">{metrics.map(([label, value, icon, color, foot]) => <article className="metric-card" key={label}><div className="metric-top"><span className="metric-label">{label}</span><span className={`metric-icon ${color}`}><Icon name={icon} /></span></div><p className="metric-value">{value}</p><span className="metric-foot"><Icon name="trend" size={14} />{foot}</span></article>)}</div>
    <div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-header"><div><h3 className="panel-title">Ritmo de vendas</h3><p className="panel-subtitle">Receita dos últimos 7 dias</p></div><span className="performance-pill">+12,8% <small>crescimento</small></span></div><div className="panel-body"><div className="bar-chart">{bars.map(bar => <div className="bar-column" key={bar.label}><div className="bar-track"><span className="bar-fill" style={{ height: `${Math.max(8, Number(bar.value) / max * 100)}%` }} data-value={money(bar.value)} /></div><span className="bar-label">{bar.label}</span></div>)}</div></div></section>
      <section className="panel"><div className="panel-header"><div><h3 className="panel-title">Canais de venda</h3><p className="panel-subtitle">Composição da receita hoje</p></div></div><div className="panel-body donut-content"><div><div className="donut" style={{ background: 'conic-gradient(#e9652d 0 46%, #26394d 46% 84%, #e9ba65 84%)' }}><div className="donut-center"><strong>{money(dashboard.revenueToday)}</strong><span>Total hoje</span></div></div><div className="chart-legend">{(dashboard.channelMix || []).map((x, i) => <span className="legend-item" key={x.label}><i className="legend-dot" style={{ background: ['#e9652d', '#26394d', '#e9ba65'][i] }} />{x.label} {x.value}%</span>)}</div></div></div></section>
    </div>
    <div className="dashboard-bottom-grid"><section className="panel"><div className="panel-header"><div><h3 className="panel-title">Pulso da operação</h3><p className="panel-subtitle">Pedidos que precisam da sua atenção</p></div><Link className="button button-sm" to="/cozinha">Ver cozinha</Link></div><div className="panel-body operation-list">{active.map(order => <div className="operation-item" key={order.id}><span className="operation-icon brand"><Icon name="chef" /></span><div className="operation-copy"><strong>{order.code} • {order.customerName}</strong><span>{order.items?.length || 0} itens · {order.type === 'DINE_IN' ? `Mesa ${order.tableNumber}` : order.type === 'DELIVERY' ? 'Delivery' : 'Retirada'}</span></div><b className="operation-value">{money(order.total)}</b></div>)}</div></section>
      <section className="panel"><div className="panel-header"><div><h3 className="panel-title">Radar inteligente</h3><p className="panel-subtitle">O Aurora encontrou oportunidades</p></div><span className="ai-badge">AURA AI</span></div><div className="panel-body insight-list"><article className="insight"><span>↑</span><div><strong>Demanda acima do previsto</strong><p>Prepare 18% mais massa para o pico das 20h.</p></div></article><article className="insight warning"><span>!</span><div><strong>Reposição sugerida</strong><p>{inventory.filter(x => Number(x.quantity) <= Number(x.minimumQuantity)).length} insumos chegaram ao estoque mínimo.</p></div></article></div></section></div>
  </div>;
}
