import { useState } from 'react';
import Icon from '../components/Icon';
import { Modal, PageHeader, Status } from '../components/UI';
import { labels, money, useApp } from '../context/AppContext';

const nextStatus = order => {
  if (order.status === 'RECEIVED') return ['PREPARING', 'Iniciar preparo'];
  if (order.status === 'PREPARING') return ['READY', 'Marcar pronto'];
  if (order.status === 'READY' && order.type === 'DELIVERY') return ['OUT_FOR_DELIVERY', 'Despachar entrega'];
  if (order.status === 'OUT_FOR_DELIVERY') return ['DELIVERED', 'Confirmar entrega'];
  if (order.status === 'READY') return ['COMPLETED', 'Concluir pedido'];
  return null;
};

export default function OrdersPage() {
  const { orders, setOrderStatus } = useApp(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL'); const [channel, setChannel] = useState('ALL'); const [selected, setSelected] = useState(null); const [view, setView] = useState('list');
  const list = orders.filter(order => (filter === 'ALL' || order.status === filter) && (channel === 'ALL' || order.type === channel) && `${order.code} ${order.customerName} ${order.customerPhone}`.toLowerCase().includes(query.toLowerCase()));
  const deliveries = orders.filter(order => order.type === 'DELIVERY' && !['COMPLETED', 'DELIVERED', 'CANCELED'].includes(order.status));
  return <div className="page-stack"><PageHeader eyebrow="Omnichannel" title="Central de pedidos" description="Histórico, produção, expedição e rastreio em todos os canais."><div className="view-toggle"><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><Icon name="receipt" />Lista</button><button className={view === 'delivery' ? 'active' : ''} onClick={() => setView('delivery')}><Icon name="truck" />Expedição <b>{deliveries.length}</b></button></div></PageHeader><div className="summary-grid"><div className="summary-card"><small>Pedidos registrados</small><strong>{orders.length}</strong></div><div className="summary-card success"><small>Concluídos</small><strong>{orders.filter(order => ['COMPLETED', 'DELIVERED'].includes(order.status)).length}</strong></div><div className="summary-card warning"><small>Em andamento</small><strong>{orders.filter(order => !['COMPLETED', 'DELIVERED', 'CANCELED'].includes(order.status)).length}</strong></div></div>
    {view === 'list' ? <section className="panel"><div className="panel-header filters-row"><div className="search-wrap"><Icon name="search" /><input className="search-input" placeholder="Buscar pedido, cliente ou telefone" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="filter-cluster"><select className="filter-select" value={channel} onChange={e => setChannel(e.target.value)}><option value="ALL">Todos os canais</option><option value="DINE_IN">Salão</option><option value="DELIVERY">Delivery</option><option value="PICKUP">Retirada</option></select><select className="filter-select" value={filter} onChange={e => setFilter(e.target.value)}><option value="ALL">Todos os status</option><option value="RECEIVED">Recebidos</option><option value="PREPARING">Em preparo</option><option value="READY">Prontos</option><option value="OUT_FOR_DELIVERY">Em rota</option><option value="COMPLETED">Concluídos</option><option value="CANCELED">Cancelados</option></select></div></div><div className="table-wrap"><table className="data-table order-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Canal</th><th>Horário</th><th>Status</th><th>Total</th><th /></tr></thead><tbody>{list.map(order => <tr key={order.id} onClick={() => setSelected(order)}><td><span className="cell-title">{order.code}</span><span className="cell-subtitle">{order.items?.reduce((sum, item) => sum + item.quantity, 0)} itens</span></td><td>{order.customerName}<span className="cell-subtitle">{order.customerPhone}</span></td><td>{labels[order.type]}{order.tableNumber ? ` · Mesa ${order.tableNumber}` : ''}</td><td>{new Date(order.createdAt).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</td><td><Status value={order.status} /></td><td><b>{money(order.total)}</b></td><td><button className="icon-button" onClick={event => { event.stopPropagation(); setSelected(order); }}><Icon name="eye" /></button></td></tr>)}</tbody></table></div></section> : <div className="delivery-board">{[['READY','Aguardando despacho'],['OUT_FOR_DELIVERY','Em rota']].map(column => <section key={column[0]}><header><div><span className={`delivery-dot ${column[0].toLowerCase()}`} /> <b>{column[1]}</b></div><strong>{deliveries.filter(order => order.status === column[0]).length}</strong></header><div>{deliveries.filter(order => order.status === column[0]).map(order => <article key={order.id}><div className="delivery-code"><span>{order.code}</span><Status value={order.status} /></div><h3>{order.customerName}</h3><p><Icon name="truck" />{order.deliveryAddress || 'Endereço não informado'}</p><small>{order.customerPhone || 'Sem telefone'} · {money(order.total)}</small>{nextStatus(order) && <button className="button button-primary" onClick={() => setOrderStatus(order.id, nextStatus(order)[0])}>{nextStatus(order)[1]}<Icon name="arrow" /></button>}</article>)}</div></section>)}</div>}
    {selected && <Modal wide title={`Pedido ${selected.code}`} subtitle={`${labels[selected.type]} · ${new Date(selected.createdAt).toLocaleString('pt-BR')}`} onClose={() => setSelected(null)}><div className="order-detail"><div className="order-detail-head"><div><span>Cliente</span><strong>{selected.customerName}</strong><small>{selected.customerPhone || 'Contato não informado'}</small></div><Status value={selected.status} /></div>{selected.deliveryAddress && <div className="delivery-address"><Icon name="truck" /><div><span>Endereço de entrega</span><strong>{selected.deliveryAddress}</strong></div></div>}<div className="order-detail-lines">{selected.items?.map((item, index) => <div key={index}><b>{item.quantity}×</b><span><strong>{item.productName}{item.halfProductName ? ` / ${item.halfProductName}` : ''}</strong><small>{[item.variantName, item.modifiers, item.notes].filter(Boolean).join(' · ')}</small></span><em>{money(item.lineTotal || item.unitPrice * item.quantity)}</em></div>)}</div>{selected.notes && <p className="order-note"><b>Observação:</b> {selected.notes}</p>}<div className="order-financial"><div><span>Subtotal</span><b>{money(selected.subtotal || selected.total)}</b></div>{Number(selected.serviceFee) > 0 && <div><span>Serviço</span><b>{money(selected.serviceFee)}</b></div>}{Number(selected.deliveryFee) > 0 && <div><span>Entrega</span><b>{money(selected.deliveryFee)}</b></div>}{Number(selected.discount) > 0 && <div className="positive"><span>Desconto</span><b>− {money(selected.discount)}</b></div>}<div className="grand"><span>Total · {selected.paymentMethod}</span><strong>{money(selected.total)}</strong></div></div><footer><button className="button" disabled={['COMPLETED','DELIVERED','CANCELED'].includes(selected.status)} onClick={() => { setOrderStatus(selected.id, 'CANCELED'); setSelected(null); }}>Cancelar pedido</button>{nextStatus(selected) && <button className="button button-primary" onClick={() => { setOrderStatus(selected.id, nextStatus(selected)[0]); setSelected({ ...selected, status: nextStatus(selected)[0] }); }}>{nextStatus(selected)[1]}<Icon name="arrow" /></button>}</footer></div></Modal>}
  </div>;
}
