import { useState } from 'react';
import Icon from '../components/Icon';
import { PageHeader, Status } from '../components/UI';
import { labels, money, useApp } from '../context/AppContext';

export default function OrdersPage() {
  const { orders } = useApp(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL');
  const list = orders.filter(o => (filter === 'ALL' || o.status === filter) && `${o.code} ${o.customerName}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-stack"><PageHeader eyebrow="Omnichannel" title="Central de pedidos" description="Histórico completo de vendas do salão, retirada e delivery." /><div className="summary-grid"><div className="summary-card"><small>Pedidos hoje</small><strong>{orders.length}</strong></div><div className="summary-card success"><small>Concluídos</small><strong>{orders.filter(o => o.status === 'COMPLETED').length}</strong></div><div className="summary-card warning"><small>Em andamento</small><strong>{orders.filter(o => !['COMPLETED', 'CANCELED'].includes(o.status)).length}</strong></div></div><section className="panel"><div className="panel-header filters-row"><div className="search-wrap"><Icon name="search" /><input className="search-input" placeholder="Buscar pedido ou cliente" value={query} onChange={e => setQuery(e.target.value)} /></div><select className="filter-select" value={filter} onChange={e => setFilter(e.target.value)}><option value="ALL">Todos os status</option><option value="RECEIVED">Recebidos</option><option value="PREPARING">Em preparo</option><option value="READY">Prontos</option><option value="COMPLETED">Concluídos</option></select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Canal</th><th>Horário</th><th>Status</th><th>Total</th></tr></thead><tbody>{list.map(o => <tr key={o.id}><td><span className="cell-title">{o.code}</span><span className="cell-subtitle">{o.items?.length} itens</span></td><td>{o.customerName}</td><td>{labels[o.type]}{o.tableNumber ? ` · Mesa ${o.tableNumber}` : ''}</td><td>{new Date(o.createdAt).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</td><td><Status value={o.status} /></td><td><b>{money(o.total)}</b></td></tr>)}</tbody></table></div></section></div>;
}
