import { useMemo, useState } from 'react';
import Icon from '../components/Icon';
import { Modal, PageHeader } from '../components/UI';
import { money, useApp } from '../context/AppContext';

const modifierOptions = [['Borda de catupiry', 10], ['Extra mozzarella', 8], ['Bacon crocante', 9], ['Azeitonas', 4], ['Sem lactose', 7]];
const paymentMethods = ['PIX', 'Cartão de crédito', 'Cartão de débito', 'Dinheiro', 'Vale-refeição'];

export default function PosPage() {
  const { products, tables, customers, settings, createOrder, validateCoupon } = useApp();
  const [category, setCategory] = useState('Todos'); const [cart, setCart] = useState([]); const [type, setType] = useState('DINE_IN');
  const [tableNumber, setTable] = useState(tables.find(t => t.status === 'AVAILABLE')?.number || 1); const [customerId, setCustomerId] = useState('');
  const [customerName, setCustomerName] = useState(''); const [customerPhone, setCustomerPhone] = useState(''); const [deliveryAddress, setDeliveryAddress] = useState('');
  const [search, setSearch] = useState(''); const [sending, setSending] = useState(false); const [customizing, setCustomizing] = useState(null);
  const [custom, setCustom] = useState({ variantName: 'Grande', halfProductId: '', modifiers: [], notes: '' }); const [checkout, setCheckout] = useState(false);
  const [coupon, setCoupon] = useState(''); const [couponResult, setCouponResult] = useState(null); const [couponError, setCouponError] = useState('');
  const [orderNotes, setOrderNotes] = useState(''); const [payments, setPayments] = useState([{ method: 'PIX', amount: '' }]);
  const categories = ['Todos', ...new Set(products.map(product => product.category))];
  const visible = products.filter(product => product.active !== false && (category === 'Todos' || product.category === category) && `${product.name} ${product.description}`.toLowerCase().includes(search.toLowerCase()));
  const pizzaProducts = products.filter(product => product.category === 'Pizzas' && product.availableForHalf !== false && product.active !== false);
  const priceFor = (product, variantName, halfProductId, modifiers = []) => {
    const half = products.find(item => item.id === Number(halfProductId)); const base = Math.max(Number(product.price), Number(half?.price || 0));
    const adjustment = Number(product.variants?.find(item => item.name === variantName)?.priceAdjustment || 0);
    return base + adjustment + modifiers.reduce((sum, name) => sum + (modifierOptions.find(item => item[0] === name)?.[1] || 0), 0);
  };
  const addDirect = product => setCart(items => [...items, { key: `${Date.now()}-${Math.random()}`, productId: product.id, name: product.name, price: Number(product.price), quantity: 1, variantName: null, halfProductId: null, modifiers: [], notes: '' }]);
  const choose = product => { if (product.category !== 'Pizzas') return addDirect(product); setCustomizing(product); setCustom({ variantName: product.variants?.find(item => item.name === 'Grande')?.name || product.variants?.[0]?.name || '', halfProductId: '', modifiers: [], notes: '' }); };
  const addCustomized = () => {
    const half = products.find(item => item.id === Number(custom.halfProductId));
    setCart(items => [...items, { key: `${Date.now()}-${Math.random()}`, productId: customizing.id, name: customizing.name, halfProductId: half?.id || null, halfName: half?.name, price: priceFor(customizing, custom.variantName, custom.halfProductId, custom.modifiers), quantity: 1, ...custom }]); setCustomizing(null);
  };
  const change = (key, delta) => setCart(items => items.map(item => item.key === key ? { ...item, quantity: item.quantity + delta } : item).filter(item => item.quantity > 0));
  const subtotal = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]);
  const serviceFee = type === 'DINE_IN' ? subtotal * Number(settings?.serviceFeePercent || 10) / 100 : 0;
  const deliveryFee = type === 'DELIVERY' ? Number(settings?.defaultDeliveryFee || 8) : 0;
  const discount = Number(couponResult?.discount || 0); const total = Math.max(0, subtotal + serviceFee + deliveryFee - discount);
  const applyCoupon = async () => { setCouponError(''); if (!coupon.trim()) return; try { setCouponResult(await validateCoupon(coupon, subtotal)); } catch (error) { setCouponResult(null); setCouponError(error.message); } };
  const openCheckout = () => { setPayments([{ method: 'PIX', amount: total.toFixed(2) }]); setCheckout(true); };
  const selectCustomer = value => { setCustomerId(value); const customer = customers.find(item => item.id === Number(value)); if (customer) { setCustomerName(customer.name); setCustomerPhone(customer.phone || ''); if (type === 'DELIVERY') setDeliveryAddress(customer.address || ''); } };
  const paid = payments.reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const finish = async event => {
    event.preventDefault(); if (!cart.length || (type === 'DELIVERY' && !deliveryAddress.trim())) return;
    setSending(true);
    try {
      await createOrder({ type, tableNumber: type === 'DINE_IN' ? Number(tableNumber) : null, customerId: customerId ? Number(customerId) : null, customerName, customerPhone, deliveryAddress: type === 'DELIVERY' ? deliveryAddress : null, couponCode: couponResult?.code || null, deliveryFee, serviceFee, notes: orderNotes, items: cart.map(({ productId, halfProductId, quantity, variantName, modifiers, notes }) => ({ productId, halfProductId, quantity, variantName, modifiers, notes })), payments: payments.map(item => ({ ...item, amount: Number(item.amount) })) });
      setCart([]); setCustomerId(''); setCustomerName(''); setCustomerPhone(''); setDeliveryAddress(''); setCoupon(''); setCouponResult(null); setOrderNotes(''); setCheckout(false);
    } finally { setSending(false); }
  };
  return <div className="page-stack"><PageHeader eyebrow="PDV inteligente" title="Novo pedido" description="Sabores, tamanhos, adicionais, cupom e pagamento dividido em um único fluxo."><span className="shortcut-hint">Atalho <b>F2</b> · novo pedido</span></PageHeader>
    <div className="order-layout"><div className="page-stack"><section className="order-context"><div className="form-field full-span"><label className="form-label">Canal de atendimento</label><div className="segmented">{[['DINE_IN','Salão'],['DELIVERY','Delivery'],['PICKUP','Retirada']].map(item => <button type="button" className={type === item[0] ? 'active' : ''} onClick={() => setType(item[0])} key={item[0]}>{item[1]}</button>)}</div></div>{type === 'DINE_IN' && <div className="form-field"><label className="form-label">Mesa</label><select value={tableNumber} onChange={e => setTable(e.target.value)}>{tables.filter(table => ['AVAILABLE', 'RESERVED'].includes(table.status)).map(table => <option key={table.id} value={table.number}>Mesa {String(table.number).padStart(2, '0')} · {table.seats} lugares</option>)}</select></div>}<div className={`form-field ${type !== 'DINE_IN' ? 'full-span' : ''}`}><label className="form-label">Cliente <span className="form-hint">opcional</span></label><select value={customerId} onChange={e => selectCustomer(e.target.value)}><option value="">Cliente avulso</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name} · {customer.loyaltyPoints || 0} pts</option>)}</select></div>{type === 'DELIVERY' && <label className="form-field full-span"><span className="form-label">Endereço de entrega</span><input required placeholder="Rua, número, complemento e bairro" value={deliveryAddress} onChange={e => setDeliveryAddress(e.target.value)} /></label>}</section>
      <section className="panel"><div className="panel-header product-toolbar"><div className="tabs">{categories.map(item => <button type="button" key={item} className={`tab ${category === item ? 'active' : ''}`} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="search-wrap"><Icon name="search" /><input className="search-input" placeholder="Buscar item" value={search} onChange={e => setSearch(e.target.value)} /></div></div><div className="product-grid">{visible.map(product => <button type="button" className="product-tile" onClick={() => choose(product)} key={product.id} style={{ '--product-accent': product.accent }}><span className="product-category">{product.category}</span><span className="product-tile-name">{product.name}</span><span className="product-tile-description">{product.description}</span><span className="product-tile-price">{money(product.price)}</span><span className="product-add"><Icon name="plus" size={15} /></span>{product.availableForHalf && <small className="half-chip">½ meio a meio</small>}</button>)}</div></section></div>
      <aside className="panel order-cart"><div className="panel-header"><div><h3 className="panel-title">Resumo do pedido</h3><p className="panel-subtitle">{cart.reduce((sum, item) => sum + item.quantity, 0)} itens adicionados</p></div><span className="order-number">NOVA</span></div>{cart.length ? <div className="cart-list">{cart.map(item => <div className="cart-item rich" key={item.key}><div><span className="cart-item-name">{item.name}{item.halfName ? ` / ${item.halfName}` : ''}</span><span className="cart-item-detail">{[item.variantName, ...(item.modifiers || [])].filter(Boolean).join(' · ')}</span><span className="cart-item-price">{money(item.price * item.quantity)}</span></div><div className="quantity-control"><button type="button" className="quantity-button" onClick={() => change(item.key, -1)}>−</button><span className="quantity-value">{item.quantity}</span><button type="button" className="quantity-button" onClick={() => change(item.key, 1)}>+</button></div></div>)}</div> : <div className="empty-cart"><span><Icon name="cart" /></span><strong>Seu pedido começa aqui</strong><p>Selecione os itens do cardápio para adicioná-los.</p></div>}<div className="coupon-box"><div><input placeholder="Cupom promocional" value={coupon} onChange={e => { setCoupon(e.target.value.toUpperCase()); setCouponError(''); }} /><button type="button" onClick={applyCoupon}>Aplicar</button></div>{couponResult && <small className="coupon-success"><Icon name="check" />{couponResult.description}</small>}{couponError && <small className="coupon-error">{couponError}</small>}</div><div className="cart-totals"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div>{serviceFee > 0 && <div><span>Serviço ({settings?.serviceFeePercent || 10}%)</span><strong>{money(serviceFee)}</strong></div>}{deliveryFee > 0 && <div><span>Entrega</span><strong>{money(deliveryFee)}</strong></div>}{discount > 0 && <div className="positive"><span>Desconto</span><strong>− {money(discount)}</strong></div>}</div><div className="cart-total"><span>Total do pedido</span><strong>{money(total)}</strong></div><div className="cart-footer"><button className="button button-primary button-lg" disabled={!cart.length || (type === 'DELIVERY' && !deliveryAddress)} onClick={openCheckout}>Pagamento e confirmação<Icon name="arrow" /></button></div></aside>
    </div>
    {customizing && <Modal wide title={customizing.name} subtitle="Personalize a pizza exatamente como o cliente pediu" onClose={() => setCustomizing(null)}><div className="customizer"><section><span className="form-label">1. Escolha o tamanho</span><div className="choice-grid">{customizing.variants?.map(variant => <button type="button" className={custom.variantName === variant.name ? 'active' : ''} key={variant.name} onClick={() => setCustom({ ...custom, variantName: variant.name })}><b>{variant.name}</b><small>{Number(variant.priceAdjustment) === 0 ? 'Preço base' : `${Number(variant.priceAdjustment) > 0 ? '+' : '−'} ${money(Math.abs(variant.priceAdjustment))}`}</small></button>)}</div></section><section><span className="form-label">2. Segundo sabor <em>opcional</em></span><select value={custom.halfProductId} onChange={e => setCustom({ ...custom, halfProductId: e.target.value })}><option value="">Pizza inteira · {customizing.name}</option>{pizzaProducts.filter(item => item.id !== customizing.id).map(item => <option key={item.id} value={item.id}>½ {customizing.name} + ½ {item.name}</option>)}</select><p className="form-explainer">No meio a meio, vale o preço do sabor de maior valor.</p></section><section><span className="form-label">3. Adicionais</span><div className="modifier-grid">{modifierOptions.map(([name, price]) => <button type="button" className={custom.modifiers.includes(name) ? 'active' : ''} key={name} onClick={() => setCustom(current => ({ ...current, modifiers: current.modifiers.includes(name) ? current.modifiers.filter(item => item !== name) : [...current.modifiers, name] }))}><span>{custom.modifiers.includes(name) ? '✓' : '+'}</span><b>{name}</b><small>+ {money(price)}</small></button>)}</div></section><label className="form-field"><span className="form-label">Observações do item</span><textarea placeholder="Ex.: assar bem, sem cebola…" value={custom.notes} onChange={e => setCustom({ ...custom, notes: e.target.value })} /></label><footer className="customizer-footer"><div><span>Valor do item</span><strong>{money(priceFor(customizing, custom.variantName, custom.halfProductId, custom.modifiers))}</strong></div><button className="button button-primary" onClick={addCustomized}>Adicionar ao pedido<Icon name="plus" /></button></footer></div></Modal>}
    {checkout && <Modal wide title="Pagamento & confirmação" subtitle="Revise os dados e divida o pagamento se necessário" onClose={() => setCheckout(false)}><form className="checkout-form" onSubmit={finish}><div className="checkout-summary"><span>Total a receber</span><strong>{money(total)}</strong><small className={Math.abs(paid - total) < .01 ? 'positive' : 'negative'}>{paid >= total ? `Troco ${money(paid - total)}` : `Faltam ${money(total - paid)}`}</small></div><div className="payment-lines"><div className="purchase-line-head"><b>Formas de pagamento</b><button type="button" className="button button-sm" onClick={() => setPayments(current => [...current, { method: 'Dinheiro', amount: Math.max(0, total - paid).toFixed(2) }])}><Icon name="plus" />Dividir pagamento</button></div>{payments.map((payment, index) => <div className="payment-line" key={index}><select value={payment.method} onChange={e => setPayments(current => current.map((item, position) => position === index ? { ...item, method: e.target.value } : item))}>{paymentMethods.map(method => <option key={method}>{method}</option>)}</select><input type="number" min="0" step=".01" value={payment.amount} onChange={e => setPayments(current => current.map((item, position) => position === index ? { ...item, amount: e.target.value } : item))} /><button type="button" className="icon-button" disabled={payments.length === 1} onClick={() => setPayments(current => current.filter((_, position) => position !== index))}>×</button></div>)}</div><label className="form-field"><span className="form-label">Nome do cliente</span><input value={customerName} onChange={e => setCustomerName(e.target.value)} placeholder="Cliente avulso" /></label><label className="form-field"><span className="form-label">Telefone</span><input value={customerPhone} onChange={e => setCustomerPhone(e.target.value)} /></label><label className="form-field full-span"><span className="form-label">Observações gerais</span><textarea value={orderNotes} onChange={e => setOrderNotes(e.target.value)} /></label><div className="form-actions"><button type="button" className="button" onClick={() => setCheckout(false)}>Voltar</button><button className="button button-primary" disabled={sending || paid + .01 < total}>{sending ? 'Enviando…' : 'Confirmar e enviar'}<Icon name="arrow" /></button></div></form></Modal>}
  </div>;
}
