import { useMemo, useState } from 'react';
import Icon from '../components/Icon';
import { PageHeader } from '../components/UI';
import { money, useApp } from '../context/AppContext';

export default function PosPage() {
  const { products, tables, createOrder } = useApp(); const [category, setCategory] = useState('Todos'); const [cart, setCart] = useState([]); const [type, setType] = useState('DINE_IN'); const [tableNumber, setTable] = useState(1); const [customerName, setCustomer] = useState(''); const [search, setSearch] = useState(''); const [sending, setSending] = useState(false);
  const categories = ['Todos', ...new Set(products.map(p => p.category))];
  const visible = products.filter(p => (category === 'Todos' || p.category === category) && p.name.toLowerCase().includes(search.toLowerCase()));
  const add = p => setCart(items => items.some(x => x.productId === p.id) ? items.map(x => x.productId === p.id ? { ...x, quantity: x.quantity + 1 } : x) : [...items, { productId: p.id, name: p.name, price: Number(p.price), quantity: 1 }]);
  const change = (id, delta) => setCart(items => items.map(x => x.productId === id ? { ...x, quantity: x.quantity + delta } : x).filter(x => x.quantity > 0));
  const subtotal = useMemo(() => cart.reduce((sum, x) => sum + x.price * x.quantity, 0), [cart]);
  const finish = async () => { if (!cart.length) return; setSending(true); await createOrder({ type, tableNumber: type === 'DINE_IN' ? Number(tableNumber) : null, customerName, paymentMethod: 'A definir', notes: '', items: cart.map(({ productId, quantity }) => ({ productId, quantity })) }); setCart([]); setCustomer(''); setSending(false); };
  return <div className="page-stack"><PageHeader eyebrow="PDV inteligente" title="Novo pedido" description="Venda em poucos toques. O pedido chega instantaneamente à cozinha." />
    <div className="order-layout"><div className="page-stack"><section className="order-context"><div className="form-field full-span"><label className="form-label">Canal de atendimento</label><div className="segmented">{[['DINE_IN', 'Salão'], ['DELIVERY', 'Delivery'], ['PICKUP', 'Retirada']].map(x => <button className={type === x[0] ? 'active' : ''} onClick={() => setType(x[0])} key={x[0]}>{x[1]}</button>)}</div></div>{type === 'DINE_IN' && <div className="form-field"><label className="form-label">Mesa</label><select value={tableNumber} onChange={e => setTable(e.target.value)}>{tables.filter(t => t.status === 'AVAILABLE').map(t => <option key={t.id} value={t.number}>Mesa {String(t.number).padStart(2, '0')} · {t.seats} lugares</option>)}</select></div>}<div className={`form-field ${type !== 'DINE_IN' ? 'full-span' : ''}`}><label className="form-label">Cliente <span className="form-hint">opcional</span></label><input placeholder="Nome ou telefone" value={customerName} onChange={e => setCustomer(e.target.value)} /></div></section>
      <section className="panel"><div className="panel-header product-toolbar"><div className="tabs">{categories.map(c => <button key={c} className={`tab ${category === c ? 'active' : ''}`} onClick={() => setCategory(c)}>{c}</button>)}</div><div className="search-wrap"><Icon name="search" /><input className="search-input" placeholder="Buscar item" value={search} onChange={e => setSearch(e.target.value)} /></div></div><div className="product-grid">{visible.map(p => <button className="product-tile" onClick={() => add(p)} key={p.id} style={{ '--product-accent': p.accent }}><span className="product-category">{p.category}</span><span className="product-tile-name">{p.name}</span><span className="product-tile-description">{p.description}</span><span className="product-tile-price">{money(p.price)}</span><span className="product-add"><Icon name="plus" size={15} /></span></button>)}</div></section></div>
      <aside className="panel order-cart"><div className="panel-header"><div><h3 className="panel-title">Resumo do pedido</h3><p className="panel-subtitle">{cart.reduce((n, x) => n + x.quantity, 0)} itens adicionados</p></div><span className="order-number">NOVA</span></div>{cart.length ? <div className="cart-list">{cart.map(item => <div className="cart-item" key={item.productId}><div><span className="cart-item-name">{item.name}</span><span className="cart-item-price">{money(item.price * item.quantity)}</span></div><div className="quantity-control"><button className="quantity-button" onClick={() => change(item.productId, -1)}>−</button><span className="quantity-value">{item.quantity}</span><button className="quantity-button" onClick={() => change(item.productId, 1)}>+</button></div></div>)}</div> : <div className="empty-cart"><span><Icon name="cart" /></span><strong>Seu pedido começa aqui</strong><p>Selecione os itens do cardápio para adicioná-los.</p></div>}<div className="cart-totals"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Taxa de serviço</span><strong>{money(type === 'DINE_IN' ? subtotal * .1 : 0)}</strong></div></div><div className="cart-total"><span>Total do pedido</span><strong>{money(type === 'DINE_IN' ? subtotal * 1.1 : subtotal)}</strong></div><div className="cart-footer"><button className="button button-primary button-lg" disabled={!cart.length || sending} onClick={finish}>{sending ? 'Enviando...' : 'Confirmar e enviar'}<Icon name="arrow" /></button></div></aside>
    </div></div>;
}
