import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import api, { apiMessage } from '../api/api';
import Icon from '../components/Icon';
import { money } from '../context/AppContext';

export default function PublicMenuPage() {
  const { token } = useParams(); const [menu, setMenu] = useState(null); const [cart, setCart] = useState([]); const [name, setName] = useState(''); const [notes, setNotes] = useState(''); const [status, setStatus] = useState('loading'); const [error, setError] = useState('');
  useEffect(() => { api.get(`/public/menu/${token}`).then(({ data }) => { setMenu(data); setStatus('ready'); }).catch(err => { setError(apiMessage(err, 'QR Code inválido ou API indisponível')); setStatus('error'); }); }, [token]);
  const total = useMemo(() => cart.reduce((sum, item) => sum + Number(item.price) * item.quantity, 0), [cart]);
  const add = product => setCart(current => current.some(item => item.id === product.id) ? current.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }]);
  const send = async () => { if (!cart.length || !name.trim()) return; setStatus('sending'); setError(''); try { const { data } = await api.post(`/public/menu/${token}/orders`, { customerName: name, notes, paymentMethod: 'Pagar no caixa', items: cart.map(item => ({ productId: item.id, quantity: item.quantity, variantName: item.category === 'Pizzas' ? 'Grande' : null, modifiers: [] })) }); setStatus('sent'); setCart([]); setError(`Pedido ${data.code}`); } catch (err) { setError(apiMessage(err)); setStatus('ready'); } };
  if (status === 'loading') return <main className="public-loading"><span className="spinner" />Preparando o cardápio…</main>;
  if (status === 'error') return <main className="public-loading"><Icon name="alert" /><h1>Não conseguimos abrir o cardápio</h1><p>{error}</p></main>;
  if (status === 'sent') return <main className="public-success"><span><Icon name="check" /></span><small>{error}</small><h1>Seu pedido já está na cozinha.</h1><p>Acompanhe o preparo com nossa equipe. Bom apetite!</p><button className="button button-primary" onClick={() => { setStatus('ready'); setError(''); }}>Fazer outro pedido</button></main>;
  const categories = [...new Set(menu.products.map(item => item.category))];
  return <main className="public-menu"><header><div className="login-brand"><span className="brand-mark"><Icon name="pizza" /></span><div><strong>{menu.business.tradeName}</strong><span>Cardápio digital · Mesa {menu.table.number}</span></div></div><div className="public-table"><Icon name="table" /><span>Mesa</span><b>{String(menu.table.number).padStart(2, '0')}</b></div></header><section className="public-hero"><span>FEITO AGORA · SERVIDO COM ALMA</span><h1>Escolha. Peça.<br /><em>Aproveite.</em></h1><p>Seu pedido vai direto para nossa cozinha.</p></section>{categories.map(category => <section className="public-category" key={category}><div><small>Da nossa cozinha</small><h2>{category}</h2></div><div className="public-products">{menu.products.filter(item => item.category === category).map(product => <article key={product.id}><div className="public-product-icon" style={{ '--accent': product.accent }}><Icon name="pizza" /></div><div><h3>{product.name}</h3><p>{product.description}</p><b>{money(product.price)}</b></div><button onClick={() => add(product)} aria-label={`Adicionar ${product.name}`}><Icon name="plus" /></button></article>)}</div></section>)}<aside className={`public-cart ${cart.length ? 'visible' : ''}`}><div><span>{cart.reduce((sum, item) => sum + item.quantity, 0)} itens</span><strong>{money(total)}</strong></div><button onClick={() => document.getElementById('public-checkout').showModal()}>Revisar pedido <Icon name="arrow" /></button></aside><dialog id="public-checkout" className="public-checkout"><button className="dialog-close" onClick={() => document.getElementById('public-checkout').close()}>×</button><span className="page-eyebrow">Quase lá</span><h2>Confirme seu pedido</h2><div className="public-cart-lines">{cart.map(item => <div key={item.id}><b>{item.quantity}× {item.name}</b><span>{money(item.price * item.quantity)}</span></div>)}</div><label className="form-field"><span className="form-label">Seu nome</span><input required value={name} onChange={e => setName(e.target.value)} /></label><label className="form-field"><span className="form-label">Observações</span><textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Ex.: sem cebola" /></label>{error && <p className="login-error">{error}</p>}<div className="public-checkout-total"><span>Total parcial</span><strong>{money(total)}</strong></div><button className="button button-primary button-lg" disabled={!name.trim() || status === 'sending'} onClick={send}>Enviar para a cozinha</button></dialog></main>;
}
