import { useMemo, useState } from 'react';
import Icon from '../components/Icon';
import { Modal, PageHeader, Status } from '../components/UI';
import { money, useApp } from '../context/AppContext';

export default function PurchasesPage() {
  const { purchases, suppliers, inventory, intelligence, addSupplier, createPurchase, receivePurchase } = useApp();
  const [tab, setTab] = useState('orders'); const [modal, setModal] = useState(null);
  const [supplierForm, setSupplierForm] = useState({ name: '', document: '', contactName: '', phone: '', email: '', leadTimeDays: 2 });
  const [form, setForm] = useState({ supplierId: suppliers[0]?.id || '', expectedDate: new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10), notes: '', items: [{ inventoryItemId: inventory[0]?.id || '', quantity: 1, unitCost: inventory[0]?.costPerUnit || 0 }] });
  const total = useMemo(() => form.items.reduce((sum, item) => sum + Number(item.quantity) * Number(item.unitCost), 0), [form.items]);
  const suggestions = intelligence?.purchaseSuggestions || [];
  const changeItem = (index, key, value) => setForm(current => ({ ...current, items: current.items.map((item, position) => position === index ? { ...item, [key]: value, ...(key === 'inventoryItemId' ? { unitCost: inventory.find(stock => stock.id === Number(value))?.costPerUnit || 0 } : {}) } : item) }));
  const submitPurchase = async event => { event.preventDefault(); const created = await createPurchase({ ...form, supplierId: Number(form.supplierId), items: form.items.map(item => ({ inventoryItemId: Number(item.inventoryItemId), quantity: Number(item.quantity), unitCost: Number(item.unitCost) })) }); if (created) setModal(null); };
  const submitSupplier = async event => { event.preventDefault(); const created = await addSupplier({ ...supplierForm, leadTimeDays: Number(supplierForm.leadTimeDays) }); if (created) setModal(null); };
  const useSuggestion = suggestion => { setForm(current => ({ ...current, supplierId: suppliers.find(s => s.name === suggestion.supplier)?.id || suppliers[0]?.id, items: [{ inventoryItemId: suggestion.inventoryItemId, quantity: Number(suggestion.suggestedQuantity), unitCost: inventory.find(i => i.id === suggestion.inventoryItemId)?.costPerUnit || 0 }] })); setModal('purchase'); };
  return <div className="page-stack"><PageHeader eyebrow="Supply chain" title="Compras & fornecedores" description="Reposição orientada por estoque, recebimento e contas a pagar integrados."><button className="button" onClick={() => setModal('supplier')}><Icon name="supplier" />Novo fornecedor</button><button className="button button-primary" onClick={() => setModal('purchase')}><Icon name="plus" />Novo pedido de compra</button></PageHeader>
    <div className="summary-grid"><div className="summary-card warning"><small>Sugestões de reposição</small><strong>{suggestions.length}</strong></div><div className="summary-card"><small>Compras em trânsito</small><strong>{purchases.filter(x => x.status === 'SENT').length}</strong></div><div className="summary-card success"><small>Fornecedores ativos</small><strong>{suppliers.filter(x => x.active !== false).length}</strong></div></div>
    <div className="tabs purchase-tabs">{[['orders', 'Pedidos de compra'], ['suggestions', 'Reposição inteligente'], ['suppliers', 'Fornecedores']].map(item => <button className={`tab ${tab === item[0] ? 'active' : ''}`} key={item[0]} onClick={() => setTab(item[0])}>{item[1]}</button>)}</div>
    {tab === 'orders' && <section className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Pedido</th><th>Fornecedor</th><th>Previsão</th><th>Itens</th><th>Status</th><th>Total</th><th /></tr></thead><tbody>{purchases.map(order => <tr key={order.id}><td><b className="cell-title">{order.code}</b><span className="cell-subtitle">{new Date(order.createdAt).toLocaleDateString('pt-BR')}</span></td><td>{order.supplierName}</td><td>{order.expectedDate ? new Date(`${order.expectedDate}T12:00:00`).toLocaleDateString('pt-BR') : '—'}</td><td>{order.items?.length || 0}</td><td><Status value={order.status} /></td><td><b>{money(order.total)}</b></td><td>{order.status === 'SENT' && <button className="button button-sm" onClick={() => receivePurchase(order.id)}>Receber</button>}</td></tr>)}</tbody></table></div></section>}
    {tab === 'suggestions' && <div className="suggestion-grid">{suggestions.length ? suggestions.map(item => <article className="suggestion-card" key={item.inventoryItemId}><span className="metric-icon amber"><Icon name="boxes" /></span><div><small>Reposição recomendada</small><h3>{item.name}</h3><p>Saldo {item.current} · comprar <b>{Number(item.suggestedQuantity).toLocaleString('pt-BR')}</b></p><span>{item.supplier}</span></div><button className="button button-primary button-sm" onClick={() => useSuggestion(item)}>Gerar compra</button></article>) : <div className="empty-premium"><span><Icon name="check" /></span><h2>Estoque saudável</h2><p>Nenhuma reposição urgente foi identificada.</p></div>}</div>}
    {tab === 'suppliers' && <div className="supplier-grid">{suppliers.map(item => <article className="supplier-card" key={item.id}><span className="supplier-logo">{item.name.split(' ').map(x => x[0]).slice(0, 2).join('')}</span><div><h3>{item.name}</h3><p>{item.contactName} · {item.phone}</p><span>{item.document}</span></div><b>{item.leadTimeDays || 0} dias<small>lead time</small></b></article>)}</div>}
    {modal === 'supplier' && <Modal title="Novo fornecedor" subtitle="Cadastre dados comerciais e prazo de entrega" onClose={() => setModal(null)}><form className="form-grid" onSubmit={submitSupplier}>{[['name','Razão social'],['document','CNPJ'],['contactName','Contato'],['phone','Telefone'],['email','E-mail']].map(([key,label]) => <label className={`form-field ${key === 'name' || key === 'email' ? 'full-span' : ''}`} key={key}><span className="form-label">{label}</span><input required={key === 'name'} value={supplierForm[key]} onChange={e => setSupplierForm({ ...supplierForm, [key]: e.target.value })} /></label>)}<label className="form-field"><span className="form-label">Prazo médio (dias)</span><input type="number" min="0" value={supplierForm.leadTimeDays} onChange={e => setSupplierForm({ ...supplierForm, leadTimeDays: e.target.value })} /></label><div className="form-actions"><button type="button" className="button" onClick={() => setModal(null)}>Cancelar</button><button className="button button-primary">Cadastrar</button></div></form></Modal>}
    {modal === 'purchase' && <Modal wide title="Novo pedido de compra" subtitle="O recebimento atualizará estoque e financeiro" onClose={() => setModal(null)}><form className="form-grid" onSubmit={submitPurchase}><label className="form-field"><span className="form-label">Fornecedor</span><select required value={form.supplierId} onChange={e => setForm({ ...form, supplierId: e.target.value })}>{suppliers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="form-field"><span className="form-label">Previsão de entrega</span><input required type="date" value={form.expectedDate} onChange={e => setForm({ ...form, expectedDate: e.target.value })} /></label><div className="purchase-lines full-span"><div className="purchase-line-head"><b>Itens da compra</b><button type="button" className="button button-sm" onClick={() => setForm(current => ({ ...current, items: [...current.items, { inventoryItemId: inventory[0]?.id, quantity: 1, unitCost: inventory[0]?.costPerUnit || 0 }] }))}><Icon name="plus" />Adicionar linha</button></div>{form.items.map((item, index) => <div className="purchase-line" key={index}><select value={item.inventoryItemId} onChange={e => changeItem(index, 'inventoryItemId', e.target.value)}>{inventory.map(stock => <option key={stock.id} value={stock.id}>{stock.name}</option>)}</select><input type="number" min=".001" step=".001" value={item.quantity} onChange={e => changeItem(index, 'quantity', e.target.value)} /><input type="number" min="0" step=".01" value={item.unitCost} onChange={e => changeItem(index, 'unitCost', e.target.value)} /><b>{money(Number(item.quantity) * Number(item.unitCost))}</b><button type="button" className="icon-button" disabled={form.items.length === 1} onClick={() => setForm(current => ({ ...current, items: current.items.filter((_, position) => position !== index) }))}>×</button></div>)}</div><label className="form-field full-span"><span className="form-label">Observações</span><textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label><div className="purchase-total full-span"><span>Total estimado</span><strong>{money(total)}</strong></div><div className="form-actions"><button type="button" className="button" onClick={() => setModal(null)}>Cancelar</button><button className="button button-primary">Enviar pedido</button></div></form></Modal>}
  </div>;
}
