import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Icon from '../components/Icon';
import { Modal, PageHeader } from '../components/UI';
import { labels, money, useApp } from '../context/AppContext';

const tabs = [
  { id: 'business', icon: 'store', label: 'Minha pizzaria', title: 'Identidade da unidade', subtitle: 'Dados comerciais exibidos no sistema e comprovantes' },
  { id: 'orders', icon: 'receipt', label: 'Pedidos e taxas', title: 'Regras de atendimento', subtitle: 'Parâmetros comerciais usados pelo PDV e delivery' },
  { id: 'team', icon: 'users', label: 'Equipe e acessos', title: 'Controle de acesso por função', subtitle: 'Privilégio mínimo para proteger a operação' },
  { id: 'payments', icon: 'wallet', label: 'Pagamentos', title: 'Formas de pagamento', subtitle: 'Meios aceitos no salão, retirada e delivery' },
  { id: 'integrations', icon: 'settings', label: 'Integrações', title: 'Ecossistema conectado', subtitle: 'Canais de venda, mensageria e emissão fiscal' },
  { id: 'security', icon: 'shield', label: 'Segurança', title: 'Segurança & conformidade', subtitle: 'Sessões, auditoria e políticas operacionais' },
];
function Field({ label, children, full = false }) { return <label className={`form-field ${full ? 'full-span' : ''}`}><span className="form-label">{label}</span>{children}</label>; }
function Toggle({ label, text, checked, onChange }) { return <button type="button" className="setting-toggle" onClick={() => onChange(!checked)}><span><strong>{label}</strong><small>{text}</small></span><i className={checked ? 'enabled' : ''}><b /></i></button>; }

export default function SettingsPage() {
  const { settings, users, branches, branchId, selectBranch, saveSettings, addUser, notify, user, online, socketOnline } = useApp();
  const [active, setActive] = useState('business'); const [form, setForm] = useState(settings); const [modal, setModal] = useState(false); const [userForm, setUserForm] = useState({ name: '', email: '', password: '', role: 'WAITER' });
  useEffect(() => setForm(settings), [settings]); const current = tabs.find(tab => tab.id === active);
  const change = (key, value) => setForm(previous => ({ ...previous, [key]: value }));
  const save = async event => { event.preventDefault(); await saveSettings({ ...form, serviceFeePercent: Number(form.serviceFeePercent), minimumDeliveryOrder: Number(form.minimumDeliveryOrder), defaultDeliveryFee: Number(form.defaultDeliveryFee), averagePrepMinutes: Number(form.averagePrepMinutes), maxDeliveryRadiusKm: Number(form.maxDeliveryRadiusKm) }); };
  const invite = async event => { event.preventDefault(); if (await addUser(userForm)) { setModal(false); setUserForm({ name: '', email: '', password: '', role: 'WAITER' }); } };
  const content = {
    business: <><div className="brand-upload"><span className="brand-mark"><Icon name="pizza" /></span><div><strong>Identidade Aurora ativa</strong><small>Logo otimizado para telas, comandas e QR Code</small></div><button type="button" className="button button-sm" onClick={() => notify('Envio de nova identidade preparado')}>Atualizar logo</button></div><Field label="Unidade ativa" full><select value={branchId} onChange={event => selectBranch(event.target.value)}>{branches.map(branch => <option value={branch.id} key={branch.id}>{branch.name} · {branch.code}</option>)}</select></Field><Field label="Nome fantasia" full><input value={form.tradeName || ''} onChange={e => change('tradeName', e.target.value)} /></Field><Field label="CNPJ"><input value={form.document || ''} onChange={e => change('document', e.target.value)} /></Field><Field label="Telefone"><input value={form.phone || ''} onChange={e => change('phone', e.target.value)} /></Field><Field label="Endereço" full><input value={form.address || ''} onChange={e => change('address', e.target.value)} /></Field></>,
    orders: <><Field label="Taxa de serviço (%)"><input type="number" min="0" step=".01" value={form.serviceFeePercent ?? 10} onChange={e => change('serviceFeePercent', e.target.value)} /></Field><Field label="Tempo médio de preparo"><input type="number" min="1" value={form.averagePrepMinutes ?? 35} onChange={e => change('averagePrepMinutes', e.target.value)} /></Field><Field label="Pedido mínimo no delivery"><input type="number" min="0" step=".01" value={form.minimumDeliveryOrder ?? 35} onChange={e => change('minimumDeliveryOrder', e.target.value)} /></Field><Field label="Taxa padrão de entrega"><input type="number" min="0" step=".01" value={form.defaultDeliveryFee ?? 8} onChange={e => change('defaultDeliveryFee', e.target.value)} /></Field><Field label="Raio máximo de entrega"><input type="number" min="1" value={form.maxDeliveryRadiusKm ?? 8} onChange={e => change('maxDeliveryRadiusKm', e.target.value)} /></Field><div className="settings-options full-span"><Toggle label="Aceitar pedidos automaticamente" text="Envia novos pedidos direto para a cozinha" checked={form.automaticAcceptance !== false} onChange={value => change('automaticAcceptance', value)} /><Toggle label="Permitir observações" text="Cliente pode adicionar instruções aos itens" checked={form.allowNotes !== false} onChange={value => change('allowNotes', value)} /><Toggle label="Imprimir comanda" text="Gera impressão ao confirmar um pedido" checked={Boolean(form.printTicket)} onChange={value => change('printTicket', value)} /></div></>,
    team: <><div className="role-overview full-span">{['ADMIN','MANAGER','CASHIER','KITCHEN','WAITER'].map(role => <div key={role}><span>{users.filter(member => member.role === role).length}</span><b>{labels[role]}</b></div>)}</div>{users.map(member => <div className="team-card full-span" key={member.id}><span className="customer-avatar">{member.name.split(' ').map(part => part[0]).slice(0, 2).join('')}</span><div><strong>{member.name}</strong><small>{member.email} · {labels[member.role]}</small></div><span className={`status-badge ${member.active ? 'status-success' : 'status-neutral'}`}>{member.active ? 'Ativo' : 'Inativo'}</span></div>)}<button type="button" className="button full-span" onClick={() => setModal(true)}><Icon name="plus" />Adicionar colaborador</button></>,
    payments: <><div className="settings-options full-span"><Toggle label="PIX" text="Confirmação rápida pelo caixa" checked={form.pixEnabled !== false} onChange={value => change('pixEnabled', value)} /><Toggle label="Cartões de crédito e débito" text="Maquininha integrada ao PDV" checked={form.cardEnabled !== false} onChange={value => change('cardEnabled', value)} /><Toggle label="Dinheiro" text="Habilita cálculo automático de troco" checked={form.cashEnabled !== false} onChange={value => change('cashEnabled', value)} /></div><Field label="Chave PIX" full><input value={form.pixKey || ''} onChange={e => change('pixKey', e.target.value)} /></Field><div className="payment-preview full-span"><span><Icon name="qr" /></span><div><small>Prévia de cobrança</small><strong>{form.pixKey || 'Cadastre sua chave PIX'}</strong><p>QR dinâmico será associado ao valor do pedido.</p></div><b>{money(89.9)}</b></div></>,
    integrations: <><div className="integration-card full-span"><span className="integration-logo green">WA</span><div><strong>WhatsApp Business</strong><small>Status automático, modelos de mensagem e histórico auditável</small></div><Link className="button button-sm" to="/automacoes">{form.whatsappConnected ? 'Gerenciar canal' : 'Configurar'}</Link></div>{[['IF','iFood','Receba pedidos direto na fila omnichannel'],['NF','Emissão fiscal','NFC-e, contingência e integração contábil'],['MP','Mercado Pago','Conciliação automática no caixa']].map(item => <div className="integration-card full-span" key={item[1]}><span className="integration-logo">{item[0]}</span><div><strong>{item[1]}</strong><small>{item[2]} · requer credenciais do provedor</small></div><button type="button" className="button button-sm" onClick={() => notify(`${item[1]}: configuração disponível na Central comercial`)}>Ver central</button></div>)}</>,
    security: <><div className="security-score full-span"><span><Icon name="shield" /></span><div><small>Postura de segurança</small><strong>Proteção avançada ativa</strong><p>JWT com expiração, senhas BCrypt, RBAC e isolamento por unidade.</p></div><b>92<small>/100</small></b></div><div className="settings-options full-span"><Toggle label="Sessões com expiração" text="Novo login obrigatório após 8 horas" checked onChange={() => notify('Política administrada pelo servidor')} /><Toggle label="Isolamento entre unidades" text="Gerentes acessam somente sua filial" checked onChange={() => notify('Política obrigatória de segurança')} /><Toggle label="Registro de ações sensíveis" text="Caixa, estoque, compras e acessos auditados" checked onChange={() => notify('Auditoria obrigatória')} /></div><Link className="button full-span" to="/auditoria"><Icon name="shield" />Abrir trilha completa de auditoria</Link><div className="connection-diagnostics full-span"><div><i className={online ? 'ok' : ''} /><span>API segura</span><b>{online ? 'Conectada' : 'Offline'}</b></div><div><i className={socketOnline ? 'ok' : ''} /><span>Canal em tempo real</span><b>{socketOnline ? 'Conectado' : 'Local'}</b></div><div><i className="ok" /><span>Sessão</span><b>{user?.role ? labels[user.role] : '—'}</b></div></div></>,
  };
  return <div className="page-stack"><PageHeader eyebrow="Central de controle" title="Configurações" description="Marca, regras, equipe, segurança e integrações em um só lugar." /><div className="settings-layout"><aside className="settings-menu">{tabs.filter(tab => tab.id !== 'team' && tab.id !== 'security' ? true : user?.role === 'ADMIN').map(tab => <button type="button" key={tab.id} className={active === tab.id ? 'active' : ''} onClick={() => setActive(tab.id)}><Icon name={tab.icon} />{tab.label}</button>)}</aside><form className="panel" onSubmit={save}><div className="panel-header"><div><h3 className="panel-title">{current.title}</h3><p className="panel-subtitle">{current.subtitle}</p></div></div><div className="panel-body form-grid settings-content" key={active}>{content[active]}{!['team','integrations','security'].includes(active) && <div className="form-actions"><button className="button button-primary">Salvar alterações</button></div>}</div></form></div>{modal && <Modal title="Novo colaborador" subtitle="Crie um acesso individual com permissão por função" onClose={() => setModal(false)}><form className="form-grid" onSubmit={invite}><Field label="Nome completo" full><input required value={userForm.name} onChange={e => setUserForm({ ...userForm, name: e.target.value })} /></Field><Field label="E-mail" full><input type="email" required value={userForm.email} onChange={e => setUserForm({ ...userForm, email: e.target.value })} /></Field><Field label="Senha inicial"><input type="password" minLength="8" required value={userForm.password} onChange={e => setUserForm({ ...userForm, password: e.target.value })} /></Field><Field label="Função"><select value={userForm.role} onChange={e => setUserForm({ ...userForm, role: e.target.value })}><option value="WAITER">Garçom</option><option value="KITCHEN">Cozinha</option><option value="CASHIER">Caixa</option><option value="MANAGER">Gerente</option><option value="ADMIN">Administrador</option></select></Field><div className="form-actions"><button type="button" className="button" onClick={() => setModal(false)}>Cancelar</button><button className="button button-primary">Criar acesso</button></div></form></Modal>}</div>;
}
