import { useState } from 'react';
import Icon from '../components/Icon';
import { PageHeader } from '../components/UI';
import { useApp } from '../context/AppContext';

const tabs = [
  { id: 'business', icon: 'store', label: 'Minha pizzaria', title: 'Identidade da pizzaria', subtitle: 'Informações exibidas no sistema e nos comprovantes' },
  { id: 'orders', icon: 'receipt', label: 'Pedidos e taxas', title: 'Pedidos e atendimento', subtitle: 'Regras comerciais aplicadas em todos os canais' },
  { id: 'team', icon: 'users', label: 'Equipe e acessos', title: 'Equipe e permissões', subtitle: 'Controle quem pode acessar cada área do sistema' },
  { id: 'payments', icon: 'wallet', label: 'Pagamentos', title: 'Formas de pagamento', subtitle: 'Meios aceitos no PDV, delivery e retirada' },
  { id: 'integrations', icon: 'settings', label: 'Integrações', title: 'Ecossistema conectado', subtitle: 'Serviços externos e automações da operação' },
];
function Field({ label, children, full = false }) { return <label className={`form-field ${full ? 'full-span' : ''}`}><span className="form-label">{label}</span>{children}</label>; }
function Toggle({ label, text, checked = true }) { const [enabled, setEnabled] = useState(checked); return <button type="button" className="setting-toggle" onClick={() => setEnabled(!enabled)}><span><strong>{label}</strong><small>{text}</small></span><i className={enabled ? 'enabled' : ''}><b /></i></button>; }

export default function SettingsPage() {
  const { notify } = useApp(); const [active, setActive] = useState('business'); const [saved, setSaved] = useState(false); const current = tabs.find(tab => tab.id === active);
  const save = event => { event.preventDefault(); setSaved(true); notify(`${current.label}: configurações salvas`); setTimeout(() => setSaved(false), 1800); };
  const content = {
    business: <><div className="brand-upload"><span className="brand-mark"><Icon name="pizza" /></span><div><strong>Logo da operação</strong><small>Identidade visual Aurora ativa</small></div><button type="button" className="button button-sm" onClick={() => notify('Gerenciador de identidade visual aberto')}>Gerenciar</button></div><Field label="Nome fantasia" full><input defaultValue="Aurora Pizza Contemporânea" /></Field><Field label="CNPJ"><input defaultValue="12.345.678/0001-90" /></Field><Field label="Telefone"><input defaultValue="(11) 3456-7890" /></Field><Field label="Endereço" full><input defaultValue="Alameda dos Sabores, 188 · São Paulo, SP" /></Field></>,
    orders: <><Field label="Taxa de serviço"><input defaultValue="10%" /></Field><Field label="Tempo médio de preparo"><input defaultValue="35 minutos" /></Field><Field label="Pedido mínimo no delivery"><input defaultValue="R$ 35,00" /></Field><Field label="Raio máximo de entrega"><input defaultValue="8 km" /></Field><div className="settings-options full-span"><Toggle label="Aceitar pedidos automaticamente" text="Envia novos pedidos direto para a cozinha" /><Toggle label="Permitir observações" text="Cliente pode adicionar instruções aos itens" /><Toggle label="Imprimir comanda" text="Gera impressão ao confirmar um pedido" checked={false} /></div></>,
    team: <>{[['DF','Davi Fernandes','Administrador geral · acesso completo','Ativo'],['MC','Marina Costa','Gerente · operação e relatórios','Ativo'],['JS','João Silva','Cozinha · acesso ao KDS','Convite']].map(user => <div className="team-card full-span" key={user[1]}><span className="customer-avatar">{user[0]}</span><div><strong>{user[1]}</strong><small>{user[2]}</small></div><span className={`status-badge ${user[3] === 'Ativo' ? 'status-success' : 'status-neutral'}`}>{user[3]}</span></div>)}<button type="button" className="button full-span" onClick={() => notify('Convite de colaborador preparado')}><Icon name="plus" />Convidar colaborador</button></>,
    payments: <><div className="settings-options full-span"><Toggle label="PIX" text="Confirmação pelo caixa" /><Toggle label="Cartões de crédito e débito" text="Maquininha integrada ao PDV" /><Toggle label="Dinheiro" text="Habilita cálculo de troco" /><Toggle label="Vale-refeição" text="Alelo, Ticket e Sodexo" checked={false} /></div><Field label="Chave PIX" full><input defaultValue="financeiro@aurorapizza.com.br" /></Field></>,
    integrations: <>{[['IF','iFood','Receba pedidos direto no Aurora','Conectar',''],['WA','WhatsApp Business','Notificações automáticas aos clientes','Conectado','green'],['NF','Emissão fiscal','NFC-e e integração contábil','Configurar','blue']].map(item => <div className="integration-card full-span" key={item[1]}><span className={`integration-logo ${item[4]}`}>{item[0]}</span><div><strong>{item[1]}</strong><small>{item[2]}</small></div>{item[3] === 'Conectado' ? <span className="status-badge status-success">Conectado</span> : <button type="button" className="button button-sm" onClick={() => notify(`${item[1]}: configuração aberta`)}>{item[3]}</button>}</div>)}</>,
  };
  return <div className="page-stack"><PageHeader eyebrow="Central de controle" title="Configurações" description="Personalize sua marca, operação e integrações." /><div className="settings-layout"><aside className="settings-menu">{tabs.map(tab => <button type="button" key={tab.id} className={active === tab.id ? 'active' : ''} onClick={() => setActive(tab.id)}><Icon name={tab.icon} />{tab.label}</button>)}</aside><form className="panel" onSubmit={save}><div className="panel-header"><div><h3 className="panel-title">{current.title}</h3><p className="panel-subtitle">{current.subtitle}</p></div></div><div className="panel-body form-grid settings-content" key={active}>{content[active]}<div className="form-actions"><button className="button button-primary">{saved ? 'Alterações salvas' : 'Salvar alterações'}</button></div></div></form></div></div>;
}
