import { useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import Icon from '../components/Icon';
import { Modal, PageHeader, Status } from '../components/UI';
import { labels, useApp } from '../context/AppContext';

const cycle = { AVAILABLE: 'CLEANING', CLEANING: 'AVAILABLE', OCCUPIED: 'CLEANING' };
export default function TablesPage() {
  const { tables, customers, reservations, setTableStatus, createReservation, updateReservation } = useApp();
  const [view, setView] = useState('floor'); const [modal, setModal] = useState(null); const [qrTable, setQrTable] = useState(null);
  const available = tables.filter(table => table.status === 'AVAILABLE');
  const [form, setForm] = useState({ tableId: available[0]?.id || '', customerId: '', customerName: '', phone: '', reservedFor: new Date(Date.now() + 2 * 3600000).toISOString().slice(0, 16), partySize: 2, notes: '' });
  const selectCustomer = id => { const customer = customers.find(item => item.id === Number(id)); setForm(current => ({ ...current, customerId: id, customerName: customer?.name || '', phone: customer?.phone || '' })); };
  const submit = async event => { event.preventDefault(); const created = await createReservation({ ...form, tableId: Number(form.tableId), customerId: form.customerId ? Number(form.customerId) : null, partySize: Number(form.partySize), reservedFor: new Date(form.reservedFor).toISOString() }); if (created) setModal(null); };
  const qrUrl = qrTable ? `${window.location.origin}/menu/${qrTable.qrToken || `mesa-${qrTable.id}`}` : '';
  return <div className="page-stack"><PageHeader eyebrow="Mapa operacional" title="Mesas, reservas & QR" description="Gerencie ocupação, agenda e autoatendimento pelo cardápio digital."><button className="button" onClick={() => setView(view === 'floor' ? 'agenda' : 'floor')}><Icon name={view === 'floor' ? 'calendar' : 'table'} />{view === 'floor' ? 'Ver agenda' : 'Ver salão'}</button><button className="button button-primary" onClick={() => setModal('reservation')}><Icon name="plus" />Nova reserva</button></PageHeader><div className="summary-grid"><div className="summary-card success"><small>Disponíveis</small><strong>{available.length}</strong></div><div className="summary-card danger"><small>Ocupadas</small><strong>{tables.filter(table => table.status === 'OCCUPIED').length}</strong></div><div className="summary-card warning"><small>Reservas próximas</small><strong>{reservations.filter(item => item.status === 'CONFIRMED').length}</strong></div></div>
    {view === 'floor' ? <section className="panel floor-panel"><div className="floor-legend"><span><i className="available" />Disponível</span><span><i className="occupied" />Ocupada</span><span><i className="reserved" />Reservada</span><span className="floor-hint">Use o menu de cada mesa para atualizar ou abrir o QR</span></div><div className="tables-grid">{tables.map(table => <article className={`table-card ${table.status.toLowerCase()}`} key={table.id}><button className="table-main-action" onClick={() => cycle[table.status] && setTableStatus(table.id, cycle[table.status])}><span className="table-icon"><Icon name="table" /></span><span className="table-number">Mesa {String(table.number).padStart(2, '0')}</span><span className="table-meta">{table.area} · {table.seats} lugares</span><span className="table-status"><Status value={table.status} /></span></button><button className="table-qr-button" onClick={() => setQrTable(table)}><Icon name="qr" />QR</button></article>)}</div></section> : <section className="panel"><div className="panel-header"><div><h3 className="panel-title">Agenda de reservas</h3><p className="panel-subtitle">Chegadas previstas e status de atendimento</p></div></div><div className="reservation-list">{reservations.map(item => <article key={item.id}><time><strong>{new Date(item.reservedFor).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</strong><span>{new Date(item.reservedFor).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })}</span></time><div><h3>{item.customerName}</h3><p>{item.partySize} pessoas · Mesa {String(item.tableNumber).padStart(2, '0')} · {item.phone}</p>{item.notes && <small>{item.notes}</small>}</div><Status value={item.status} /><div className="reservation-actions">{item.status === 'CONFIRMED' && <><button className="button button-sm button-primary" onClick={() => updateReservation(item.id, 'SEATED')}>Sentar cliente</button><button className="button button-sm" onClick={() => updateReservation(item.id, 'CANCELED')}>Cancelar</button></>}{item.status === 'SEATED' && <button className="button button-sm" onClick={() => updateReservation(item.id, 'COMPLETED')}>Finalizar</button>}</div></article>)}</div></section>}
    {modal === 'reservation' && <Modal title="Nova reserva" subtitle="Confirme mesa, horário e contato do cliente" onClose={() => setModal(null)}><form className="form-grid" onSubmit={submit}><label className="form-field"><span className="form-label">Mesa</span><select required value={form.tableId} onChange={e => setForm({ ...form, tableId: e.target.value })}>{available.map(table => <option key={table.id} value={table.id}>Mesa {table.number} · {table.seats} lugares</option>)}</select></label><label className="form-field"><span className="form-label">Data e horário</span><input required type="datetime-local" value={form.reservedFor} onChange={e => setForm({ ...form, reservedFor: e.target.value })} /></label><label className="form-field full-span"><span className="form-label">Cliente cadastrado <span className="form-hint">opcional</span></span><select value={form.customerId} onChange={e => selectCustomer(e.target.value)}><option value="">Informar manualmente</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><label className="form-field"><span className="form-label">Nome</span><input required value={form.customerName} onChange={e => setForm({ ...form, customerName: e.target.value })} /></label><label className="form-field"><span className="form-label">Telefone</span><input required value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label className="form-field"><span className="form-label">Número de pessoas</span><input required type="number" min="1" max="20" value={form.partySize} onChange={e => setForm({ ...form, partySize: e.target.value })} /></label><label className="form-field"><span className="form-label">Observações</span><input value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label><div className="form-actions"><button type="button" className="button" onClick={() => setModal(null)}>Cancelar</button><button className="button button-primary">Confirmar reserva</button></div></form></Modal>}
    {qrTable && <Modal title={`QR Code · Mesa ${qrTable.number}`} subtitle="O cliente escaneia, escolhe e envia o pedido para a cozinha" onClose={() => setQrTable(null)}><div className="qr-modal"><div className="qr-frame"><QRCodeSVG value={qrUrl} size={220} level="H" marginSize={2} fgColor="#19222e" /></div><strong>{qrUrl}</strong><p>Imprima este código e posicione-o na mesa. Cada QR é exclusivo e vinculado à unidade.</p><div><button className="button" onClick={() => navigator.clipboard?.writeText(qrUrl)}><Icon name="qr" />Copiar link</button><button className="button button-primary" onClick={() => window.print()}><Icon name="download" />Imprimir QR</button></div></div></Modal>}
  </div>;
}
